### ISSUE TITLE
Cluster needs review: chicken edouard foie gras herriot mushrooms sauce supreme truffle

### ISSUE THREAD

**Issue by katierawson** [trevormunoz/public-fare-data#13]
fingerprint: chicken edouard foie gras herriot mushrooms sauce supreme truffle

ingredient list next to dish ?
- [http://menus.nypl.org/menu_items/539476/edit](http://menus.nypl.org/menu_items/539476/edit)

**Comment by trevormunoz** [comment]
I think we decided to drop ingredients from names
