### ISSUE TITLE
Cluster needs review: chocolate

### ISSUE THREAD

**Issue by katierawson** [trevormunoz/public-fare-data#14]
fingerprint: chocolate

Sometimes chocolate is hot chocolate, sometimes chocolate ice cream, etc.
- [http://menus.nypl.org/menu_items/232430/edit](http://menus.nypl.org/menu_items/232430/edit)
- [http://menus.nypl.org/menu_items/112789/edit](http://menus.nypl.org/menu_items/112789/edit)
- [http://menus.nypl.org/menu_items/75239/edit](http://menus.nypl.org/menu_items/75239/edit)
- [http://menus.nypl.org/menu_items/482066/edit](http://menus.nypl.org/menu_items/482066/edit)
- [http://menus.nypl.org/menu_items/1103165/edit](http://menus.nypl.org/menu_items/1103165/edit)
- [http://menus.nypl.org/menu_items/503626/edit](http://menus.nypl.org/menu_items/503626/edit)
- [http://menus.nypl.org/menu_items/316672/edit](http://menus.nypl.org/menu_items/316672/edit)

**Comment by trevormunoz** [comment]
Disambiguated
