### ISSUE TITLE
Cluster needs review: bacon eggs scrambled with

### ISSUE THREAD

**Issue by katierawson** [trevormunoz/public-fare-data#16]
fingerprint: bacon eggs scrambled with

is the order of these foods transposable or do we need to separate out bacon with scrambled eggs from scrambled eggs with bacon?
- [http://menus.nypl.org/menu_items/10533/edit](http://menus.nypl.org/menu_items/10533/edit)
- [http://menus.nypl.org/menu_items/89292/edit](http://menus.nypl.org/menu_items/89292/edit)
- [http://menus.nypl.org/menu_items/1035879/edit](http://menus.nypl.org/menu_items/1035879/edit)
- [http://menus.nypl.org/menu_items/187920/edit](http://menus.nypl.org/menu_items/187920/edit)
- [http://menus.nypl.org/menu_items/462121/edit](http://menus.nypl.org/menu_items/462121/edit)
- [http://menus.nypl.org/menu_items/556601/edit](http://menus.nypl.org/menu_items/556601/edit)
- [http://menus.nypl.org/menu_items/1212219/edit](http://menus.nypl.org/menu_items/1212219/edit)
- [http://menus.nypl.org/menu_items/1255727/edit](http://menus.nypl.org/menu_items/1255727/edit)
- [http://menus.nypl.org/menu_items/1309399/edit](http://menus.nypl.org/menu_items/1309399/edit)
- [http://menus.nypl.org/menu_items/860658/edit](http://menus.nypl.org/menu_items/860658/edit)
- [http://menus.nypl.org/menu_items/983601/edit](http://menus.nypl.org/menu_items/983601/edit)
- [http://menus.nypl.org/menu_items/1106858/edit](http://menus.nypl.org/menu_items/1106858/edit)
- [http://menus.nypl.org/menu_items/1348526/edit](http://menus.nypl.org/menu_items/1348526/edit)
- [http://menus.nypl.org/menu_items/559357/edit](http://menus.nypl.org/menu_items/559357/edit)
- [http://menus.nypl.org/menu_items/298489/edit](http://menus.nypl.org/menu_items/298489/edit)
- [http://menus.nypl.org/menu_items/343873/edit](http://menus.nypl.org/menu_items/343873/edit)

**Comment by trevormunoz** [comment]
I don't think the order is significant
