### ISSUE TITLE
Cluster needs review: mutton

### ISSUE THREAD

**Issue by katierawson** [trevormunoz/public-fare-data#24]
fingerprint: /mutton/  

mutton " is mutton chops.  
- [http://menus.nypl.org/menu_items/17267/edit](http://menus.nypl.org/menu_items/17267/edit)
- [http://menus.nypl.org/menu_items/1205864/edit](http://menus.nypl.org/menu_items/1205864/edit)
- [http://menus.nypl.org/menu_items/1182810/edit](http://menus.nypl.org/menu_items/1182810/edit)
- [http://menus.nypl.org/menu_items/31754/edit](http://menus.nypl.org/menu_items/31754/edit)
- [http://menus.nypl.org/menu_items/57806/edit](http://menus.nypl.org/menu_items/57806/edit)

**Comment by trevormunoz** [comment]
Fixed @ NYPL
