### ISSUE TITLE
Cluster needs review: sauce tomato

### ISSUE THREAD

**Issue by katierawson** [trevormunoz/public-fare-data#27]
fingerprint: /sauce tomato/  

" tomato sauce is a food with tomato sauce (several on the menu)  
- [http://menus.nypl.org/menu_items/63114/edit](http://menus.nypl.org/menu_items/63114/edit)
- [http://menus.nypl.org/menu_items/1285296/edit](http://menus.nypl.org/menu_items/1285296/edit)
- [http://menus.nypl.org/menu_items/1346269/edit](http://menus.nypl.org/menu_items/1346269/edit)
- [http://menus.nypl.org/menu_items/77433/edit](http://menus.nypl.org/menu_items/77433/edit)
- [http://menus.nypl.org/menu_items/123496/edit](http://menus.nypl.org/menu_items/123496/edit)

**Comment by trevormunoz** [comment]
Fixed @ NYPL
