### ISSUE TITLE
Cluster needs review: pears

### ISSUE THREAD

**Issue by katierawson** [trevormunoz/public-fare-data#29]
fingerprint: /pears/  

" pears is brandy pears  
- [http://menus.nypl.org/menu_items/174/edit](http://menus.nypl.org/menu_items/174/edit)
- [http://menus.nypl.org/menu_items/1228176/edit](http://menus.nypl.org/menu_items/1228176/edit)
- [http://menus.nypl.org/menu_items/1119375/edit](http://menus.nypl.org/menu_items/1119375/edit)
- [http://menus.nypl.org/menu_items/410681/edit](http://menus.nypl.org/menu_items/410681/edit)
- [http://menus.nypl.org/menu_items/448976/edit](http://menus.nypl.org/menu_items/448976/edit)
- [http://menus.nypl.org/menu_items/149932/edit](http://menus.nypl.org/menu_items/149932/edit)
- [http://menus.nypl.org/menu_items/108095/edit](http://menus.nypl.org/menu_items/108095/edit)

**Comment by trevormunoz** [comment]
Data updated at NYPL site
